spring.application.name=ScrapeX

build configuration is set of instrctions that tells your build tool
(like Maven or Gradle in java, or MSbuild in .Net) how to compile,and run your application.It defines
spring.datasouce.url=
spring.datasouce.username=
spring.datasource.password=
spring.data.jpa.
